fix: [issue](https://github.com/microsoft/TypeScript/issues/62508#issuecomment-3348649259) typescript error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.